### ISSUE TITLE
Deleting a cell?!

### ISSUE THREAD

**Issue by fatgue** [pi3r0/PHFParallaxBackgroundCell#1]
Hi,
thanks for the awesome work. I have problems to delete a cell, what is the best way to delete it?

**Comment by pi3r0** [comment]
Hi,

Sorry for the late response but you can delete a cell with this method :
_myTableview.deletedeleteRowsAtIndexPaths(indexPaths: [AnyObject],
withRowAnimation: UITableViewRowAnimation)

And with delete the object at index in your datasource array, in my code
it's _images.

Hope it will help you.

Best regards.

Pierre

2015-01-09 10:47 GMT+01:00 fatgue notifications@github.com:

> Hi,
> thanks for the awesome work. I have problems to delete a cell, what is the
> best way to delete it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pi3r0/PHFParallaxBackgroundCell/issues/1.

## 

[image: logo] http://www.procheo.fr
_PIERRE HOUGUET_  •  _DÉVELOPPEUR iOS_
Tél : +33 1 83 64 49 60 https://www.procheo.fr
2 Avenue de la Cristallerie - 92310 Sèvres - France   •  Google Maps
https://www.google.fr/maps?q=2+Avenue+de+la+Cristallerie,+S%C3%A8vres&hl=fr&ie=UTF8&sll=48.858859,2.34706&sspn=0.366826,1.056747&oq=2+avenue+de+la+critallerie&hnear=2+Avenue+de+la+Cristallerie,+92310+S%C3%A8vres,+Hauts-de-Seine,+%C3%8Ele-de-France&t=m&z=16
www.procheo.fr http://www.procheo.com

**Comment by fatgue** [comment]
sorry for the late response :(. Thanks for the hint but i have strange problem if i want delete a row. The image of the row which will be deleted covers the bottom row. See picture http://picload.org/view/cpilolr/bildschirmfoto2015-02-25um16.3.png.html

**Comment by pi3r0** [comment]
Can i have a sample of your code for testing. It will be more easier to give u an answer. 

Pierre,

Envoyé de mon iPhone

**Comment by fatgue** [comment]
You don't need my code insert only this code in yours. The try to delete a row and you will see what i mean :) 

func tableView(tableView: UITableView, commitEditingStyle editingStyle: UITableViewCellEditingStyle, forRowAtIndexPath indexPath: NSIndexPath) {
        if(editingStyle == UITableViewCellEditingStyle.Delete){
            _imageTableView.deleteRowsAtIndexPaths([indexPath], withRowAnimation: UITableViewRowAnimation.Bottom)
            _imageTableView.reloadData()

```
    }
}
```

**Comment by pi3r0** [comment]
Hi, i'm late but i have test and this is work for me, i suggest to use this code : 
   func tableView(tableView: UITableView, commitEditingStyle editingStyle: UITableViewCellEditingStyle, forRowAtIndexPath indexPath: NSIndexPath) {

```
    if (editingStyle == UITableViewCellEditingStyle.Delete) {
        tableView.beginUpdates();
        yourarray.removeAtIndex(indexPath.row);
        tableView.deleteRowsAtIndexPaths([indexPath], withRowAnimation: UITableViewRowAnimation.Fade);
        tableView.endUpdates();
    }
}
```

The tableView.beginUpdates and  tableView.endUpdates() are mandatory not reloadData(), put this in your code. Hope it will answer your question. 

Pierre,
