### ISSUE TITLE
scrollViewDidScroll method has an error

### ISSUE THREAD

**Issue by Mwiti** [pi3r0/PHFParallaxBackgroundCell#2]
Attached is a screen shot of the error.

![screen shot 2015-05-09 at 9 45 14 am](https://cloud.githubusercontent.com/assets/4980424/7549078/3aa77f96-f630-11e4-89e6-d8930e937d12.png)

its the only error I'm getting. can't find a way around it. (PS: Im not very experienced here). Please help. Thanks

**Comment by pi3r0** [comment]
Sorry for the late response, i find the errors due to the UIScrollViewDelegate declaration on top of the class. Just delete it, it provokes the conflict but you can update the code, i fix some issues due to the changes on swift. Thanks for the support.
